

#Setup and Data Import

```{r}
rm(list = ls())
source("JT_Hrach_func.R")
call_libraries()
'%+%' <- ggplot2::'%+%'

df1 <- read.csv(file = "Final_data_chunk_1.csv")
df2 <- read.csv(file = "Final_data_chunk_2.csv")
df3 <- read.csv(file = "Final_data_chunk_3.csv")
df4 <- read.csv(file = "Final_data_chunk_4.csv")
df5 <- read.csv(file = "Final_data_chunk_5.csv")
df6 <- read.csv(file = "Final_data_chunk_6.csv")

raw.data <- do.call("rbind", list(df1, df2, df3, df4, df5, df6))

# Theme
th <- call_aesthethics(16) +
  theme(axis.text.x = element_text(angle = 45, hjust = 0.95), legend.position = 'none')

#Data from first-time participants selecting the shortest version of the task
ft.data <- raw.data %>% 
  filter(repeat. == "First Time") %>%
  filter(gameIndex == "easy") %>%
  filter(numtar == 1) %>%
  filter(TN <= 90) # selecting the first 90 trials of the task

```


#Core plots 

```{r}
p1 <- ft.data %>% 
  group_by(TN, Block, FB) %>%
  dplyr::summarise(Hand_mean = mean(HandFlip, na.rm = TRUE), Hand_sem = std.error(HandFlip, na.rm = TRUE) ) %>%
  ggplot(aes(x = TN, y = Hand_mean, group = factor(Block), shape = factor(FB), color = )) + 
  annotate(x = c(0, 0, 0, 90.5), 
           xend = c(90.5, 90.5, 90.5, 90.5), 
           y = c(0, 45, 0, 0), 
           yend = c(0, 45, 0, 0), alpha= .5, color = 'light grey', 'segment') +
  geom_ribbon(aes(ymin = Hand_mean - Hand_sem, ymax = Hand_mean + Hand_sem), alpha = 0.25) +
  geom_point(size = 0.5) +
  scale_x_continuous(breaks = c(0, 30, 84, 90) ) + 
  geom_vline(xintercept=c(30.5, 84.5, 90.5), linetype="longdash", alpha = .7, color = 'lightgrey') +
  scale_y_continuous(breaks = seq(-45, 45, 15) ) +
  scale_colour_brewer(palette = "Set1") +
  scale_shape_manual(values=c(1, 16), guide = FALSE) + 
  labs(x= 'Trial #', y = 'Hand Angle (°)') +th
p1

```


#Histograms

```{r}

mousedem <- ft.data %>%
  mutate(
    mousetype = case_when(
      mousetype == 'idk' ~ "other",
      mousetype == 'trackpad' ~ "track pad",
      mousetype == 'trackball' ~ "track ball",
      mousetype == 'optical' ~ "optical"
    )
  ) %>%
  filter(TN == 1) %>%
  ggplot(aes(x = mousetype, fill = as.factor(cyl))) +
  theme_minimal() +
  geom_bar(fill = rgb(0.1, 0.4, 0.5, 0.7)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 0.95))

sexdem <- ft.data %>%
  filter(TN == 1) %>%
  ggplot(aes(x = sex, fill = as.factor(cyl))) +
  theme_minimal() +
  geom_bar(fill = rgb(0.1, 0.4, 0.5, 0.7)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 0.95))
sexdem


racedem <- ft.data %>%
  filter(TN == 1) %>%
  ggplot(aes(x = racialorigin, fill = as.factor(cyl))) +
  theme_minimal() +
  geom_bar(fill = rgb(0.1, 0.4, 0.5, 0.7)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 0.95))
racedem


handdem <- ft.data %>%
  mutate(
    Handedness = case_when(
      Handedness == 'lefth' ~ "lefty",
      Handedness == 'righth' ~ "righty",
      Handedness == 'bothh' ~ "ambi."
    )
  ) %>%
  filter(TN == 1) %>%
  ggplot(aes(x = Handedness, fill = as.factor(cyl))) +
  theme_minimal() +
  geom_bar(fill = rgb(0.1, 0.4, 0.5, 0.7)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 0.95))
handdem

```

#Target Number

```{r}

mult_targ <- raw.data %>%
  filter(numtar == 1 & TN <91 | 
           numtar == 2 & TN <181 |
           numtar == 4 & TN <361 |
           numtar == 8 & TN <721) %>% 
  mutate(cycle = ceiling(TN/numtar)) %>%
  group_by(Subject.ID, cycle, Block, FB, numtar) %>%
  dplyr::summarise(HandFlip = mean(HandFlip, na.rm = TRUE))

p6 <- mult_targ %>% 
  group_by(cycle, Block, FB, numtar) %>%
  dplyr::summarise(Hand_mean = mean(HandFlip, na.rm = TRUE), Hand_sem = std.error(HandFlip, na.rm = TRUE) ) %>%
  ggplot(aes(x = cycle, y = Hand_mean, group = factor(Block), shape = factor(FB), color = )) + 
  annotate(x = c(0, 0, 0, 90.5), 
           xend = c(90.5, 90.5, 90.5, 90.5), 
           y = c(0, 45, 0, 0), 
           yend = c(0, 45, 0, 0), alpha= .5, color = 'light grey', 'segment') +
  geom_ribbon(aes(ymin = Hand_mean - Hand_sem, ymax = Hand_mean + Hand_sem), alpha = 0.25) +
  geom_point(size = 0.5) +
  scale_x_continuous(breaks = c(0, 30, 84, 90) ) + 
  geom_vline(xintercept=c(30.5, 84.5, 90.5), linetype="longdash", alpha = .7, color = 'lightgrey') +
  scale_y_continuous(breaks = seq(-45, 45, 15) ) +
  #scale_colour_brewer(palette = "Set1") +
  scale_shape_manual(values=c(1, 16), guide = FALSE) + 
  labs(x= 'Cycle #', y = 'Hand Angle (°)')+
  scale_colour_manual("",values=c('orange', 'deepskyblue4'))+
  scale_fill_manual("",values=c('orange', 'deepskyblue4'))

targdata <- mult_targ %>%
  filter(numtar <= 2) %>%
  group_by(cycle, Block, FB, numtar) %>%
  dplyr::summarise(Hand_mean = mean(HandFlip, na.rm = TRUE), Hand_sem = std.error(HandFlip, na.rm = TRUE) )

targplot <- p6 %+% targdata + aes(fill = factor(numtar), group = interaction(factor(Block), factor(numtar))) + 
  geom_point (aes(color = factor(numtar)), size = 0.5) + 
  geom_ribbon(aes(ymin = Hand_mean - Hand_sem, ymax = Hand_mean + Hand_sem), alpha = 0.05) +
  labs(fill = '', color = '') +
  scale_colour_manual("",values=c('orange', 'deepskyblue4'))+
  scale_fill_manual("",values=c('orange', 'deepskyblue4'))+ th
targplot

```

#Variability

```{r}
dat <- ft.data %>% 
  group_by(Subject.ID) %>%
  dplyr::summarise(AE = mean(HandFlip, na.rm = TRUE))

demo_vars <- ft.data %>% filter(TN > 1 & TN <= 30) %>%
  group_by(Subject.ID,
           Age, 
           Sleep, 
           ComputerUsage,
           Handedness,
           education, 
           rating, 
           mousetype, 
           racialorigin, 
           sex, 
           vision, 
           clumsy, 
           videogames, 
           major,
           browsertype,
           screensize,
           cardinal,
           CCW,
           NeuroDisease) %>%
  
  dplyr::summarise(RT_mean_baseline = mean(RT, na.rm = TRUE),
                   MT_mean_baseline = mean(MT, na.rm = TRUE),
                   ST_mean_baseline = mean(ST, na.rm = TRUE),
                   Var_sum_baseline = sum(variability, na.rm = TRUE))


ft.data.w.demo <- full_join(dat, demo_vars, by = c("Subject.ID")) %>% drop_na()

var_subs <- ft.data.w.demo %>% 
  mutate(Above = ifelse(Var_sum_baseline >= median(Var_sum_baseline), "Above", "Below")) %>%
  select(Subject.ID, Above)

vardata <- na.omit(full_join(ft.data, var_subs, by = c("Subject.ID"))) %>% 
  group_by(TN, Block, FB, Above) %>%
  dplyr::summarise(Hand_mean = mean(HandFlip, na.rm = TRUE), Hand_sem = std.error(HandFlip, na.rm = TRUE) )

varplot <- p1 %+% vardata + aes(fill = factor(Above), group = interaction(factor(Block), factor(Above))) + 
  geom_point (aes(color = factor(Above)), size = 0.5) + 
  geom_ribbon(aes(ymin = Hand_mean - Hand_sem, ymax = Hand_mean + Hand_sem), alpha = 0.05) +
  labs(fill = '', color = '')+
  scale_colour_manual("",values=c('orange', 'deepskyblue4'))+
  scale_fill_manual("",values=c('orange', 'deepskyblue4'))
varplot

```


#Movement Time

```{r}

MT_subs <- ft.data.w.demo%>% 
  mutate(Above = ifelse(MT_mean_baseline >= median(MT_mean_baseline), 
                "Above", "Below")) %>%
  select(Subject.ID, Above)

MTdata <- na.omit(full_join(ft.data, MT_subs, by = c("Subject.ID"))) %>% 
  group_by(TN, Block, FB, Above) %>%
  dplyr::summarise(Hand_mean = mean(HandFlip, na.rm = TRUE), Hand_sem = std.error(HandFlip, na.rm = TRUE) )

MTplot <- p1 %+% MTdata + aes(fill = factor(Above), group = interaction(factor(Block), factor(Above))) + 
  geom_point (aes(color = factor(Above)), size = 0.5) + 
  geom_ribbon(aes(ymin = Hand_mean - Hand_sem, ymax = Hand_mean + Hand_sem), alpha = 0.05) +
  labs(fill = '', color = '')+
  scale_colour_manual("",values=c('orange', 'deepskyblue4'))+
  scale_fill_manual("",values=c('orange', 'deepskyblue4'))
MTplot

```


#Reaction time

```{r}

RT_subs <- ft.data.w.demo %>% 
  mutate(Above = ifelse(RT_mean_baseline >= median(RT_mean_baseline), 
                "Above", "Below")) %>%
  select(Subject.ID, Above)

RTdata <- na.omit(full_join(ft.data, RT_subs, by = c("Subject.ID"))) %>% 
  group_by(TN, Block, FB, Above) %>%
  dplyr::summarise(Hand_mean = mean(HandFlip, na.rm = TRUE), Hand_sem = std.error(HandFlip, na.rm = TRUE) )

RTplot <- p1 %+% RTdata + aes(fill = factor(Above), group = interaction(factor(Block), factor(Above))) + 
  geom_point (aes(color = factor(Above)), size = 0.5) + 
  geom_ribbon(aes(ymin = Hand_mean - Hand_sem, ymax = Hand_mean + Hand_sem), alpha = 0.05) +
  labs(fill = '', color = '')+
  scale_colour_manual("",values=c('orange', 'deepskyblue4'))+
  scale_fill_manual("",values=c('orange', 'deepskyblue4'))
RTplot

```


#Sex

```{r}

sexdata <- ft.data %>% 
  filter(sex != "other") %>%
  group_by(TN, Block, FB, sex) %>%
  dplyr::summarise(Hand_mean = mean(HandFlip, na.rm = TRUE), Hand_sem = std.error(HandFlip, na.rm = TRUE) )

sexplot <- p1 %+% sexdata + aes(fill = sex, group = interaction(factor(Block), sex)) + 
  geom_point (aes(color = sex), size = 0.5) + 
  geom_ribbon(aes(ymin = Hand_mean - Hand_sem, ymax = Hand_mean + Hand_sem, fill = sex), alpha = 0.1) +
  labs(fill = '', color = '') +
  scale_colour_manual("",values=c('orange', 'deepskyblue4'))+
  scale_fill_manual("",values=c('orange', 'deepskyblue4'))
sexplot

```
#Neurological Pathology

```{r}

neurodata <- ft.data %>% na.omit() %>%
  group_by(TN, Block, FB, NeuroDisease) %>%
  dplyr::summarise(Hand_mean = mean(HandFlip, na.rm = TRUE), Hand_sem = std.error(HandFlip, na.rm = TRUE) )

neuroplot <- p1 %+% neurodata + aes(fill = as.factor(NeuroDisease), group = interaction(factor(Block), as.factor(NeuroDisease))) + 
  geom_point (aes(color = as.factor(NeuroDisease)), size = 0.5) + 
  geom_ribbon(aes(ymin = Hand_mean - Hand_sem, ymax = Hand_mean + Hand_sem, fill = as.factor(NeuroDisease)), alpha = 0.1) +
  labs(fill = '', color = '') +
  scale_colour_manual("",values=c('orange', 'deepskyblue4'))+
  scale_fill_manual("",values=c('orange', 'deepskyblue4'))
neuroplot

```

#Age 

```{r}

# Median Split: median(ft.data$Age[ft.data$TN == 1])

agedata <- ft.data %>% 
  mutate(Age_Group = case_when(Age <= 40 ~ '9-40', 
                            Age > 40 ~ '41-100')) %>%
  group_by(TN, Block, FB, Age_Group) %>%
  dplyr::summarise(Hand_mean = mean(HandFlip, na.rm = TRUE), Hand_sem = std.error(HandFlip, na.rm = TRUE) )

ageplot <- p1 %+% agedata + aes(fill = factor(Age_Group), group = interaction(factor(Block), factor(Age_Group))) + 
  geom_point (aes(color = factor(Age_Group)), size = 0.5) + 
  #geom_line(aes(color = factor(Age_Group))) +
  geom_ribbon(aes(ymin = Hand_mean - Hand_sem, ymax = Hand_mean + Hand_sem), alpha = 0.05) +
  labs(fill = '', color = '')+
  scale_colour_manual("",values=c('orange', 'deepskyblue4'))+
  scale_fill_manual("",values=c('orange', 'deepskyblue4'))
ageplot

``` 


#Mouse

```{r}
mousedata <- ft.data %>% 
  filter(mousetype %in% c('trackpad', 'optical')) %>%
  mutate(mousetype = ifelse(mousetype == 'optical', 'Mouse', 'Trackpad')) %>%
  group_by(TN, Block, FB, mousetype) %>%
  dplyr::summarise(Hand_mean = mean(HandFlip, na.rm = TRUE), Hand_sem = std.error(HandFlip, na.rm = TRUE) )

mouseplot <- p1 %+% mousedata + aes(fill = factor(mousetype), group = interaction(factor(Block), factor(mousetype))) + 
  geom_point (aes(color = factor(mousetype)), size = 0.5) + 
  geom_ribbon(aes(ymin = Hand_mean - Hand_sem, ymax = Hand_mean + Hand_sem), alpha = 0.05) +
  labs(fill = '', color = '')+
  scale_colour_manual("",values=c('orange', 'deepskyblue4'))+
  scale_fill_manual("",values=c('orange', 'deepskyblue4'))
mouseplot

```


#Handedness

```{r}

handeddata <- ft.data %>% 
  group_by(TN, Block, FB, Handedness) %>%
  dplyr::summarise(Hand_mean = mean(HandFlip, na.rm = TRUE), Hand_sem = std.error(HandFlip, na.rm = TRUE) )

handed_plot <- p1 %+% handeddata + aes(fill = Handedness, group = interaction(factor(Block), Handedness)) + 
  geom_point (aes(color = Handedness), size = 0.5) + 
  geom_ribbon(aes(ymin = Hand_mean - Hand_sem, ymax = Hand_mean + Hand_sem), alpha = 0.05) +
  labs(fill = '', color = '')+
  scale_colour_manual("",values=c('orange', 'deepskyblue4', 'grey40'))+
  scale_fill_manual("",values=c('orange', 'deepskyblue4', 'grey40'))
handed_plot

```


#Screen size

```{r}

screen_subs <- ft.data.w.demo%>% 
  mutate(Above = ifelse(screensize >= median(screensize), "Above", "Below")) %>%
  select(Subject.ID, Above)

screendata <- na.omit(full_join(ft.data, screen_subs, by = c("Subject.ID"))) %>% 
  group_by(TN, Block, FB, Above) %>%
  dplyr::summarise(Hand_mean = mean(HandFlip, na.rm = TRUE), Hand_sem = std.error(HandFlip, na.rm = TRUE) )

screenplot <- p1 %+% screendata + aes(fill = factor(Above), group = interaction(factor(Block), factor(Above))) + 
  geom_point (aes(color = factor(Above)), size = 0.5) + 
  geom_ribbon(aes(ymin = Hand_mean - Hand_sem, ymax = Hand_mean + Hand_sem), alpha = 0.05) +
  labs(fill = '', color = '')+
  scale_colour_manual("",values=c('orange', 'deepskyblue4'))+
  scale_fill_manual("",values=c('orange', 'deepskyblue4'))
screenplot

```


#Directionality

```{r}

directiondata <- ft.data %>% 
  mutate(CCW = ifelse(CCW == TRUE, 'CCW', 'CW')) %>%
  group_by(TN, Block, FB, CCW) %>%
  dplyr::summarise(Hand_mean = mean(HandFlip, na.rm = TRUE), Hand_sem = std.error(HandFlip, na.rm = TRUE) )

directionplot <- p1 %+% directiondata + aes(fill = factor(CCW), group = interaction(factor(Block), factor(CCW))) + 
  geom_point (aes(color = factor(CCW)), size = 0.5) + 
  geom_ribbon(aes(ymin = Hand_mean - Hand_sem, ymax = Hand_mean + Hand_sem), alpha = 0.05) +
  labs(fill = '', color = '')+
  scale_colour_manual("",values=c('orange', 'deepskyblue4'))+
  scale_fill_manual("",values=c('orange', 'deepskyblue4'))

```


#Targets

```{r}

targetdata <- ft.data %>% 
  mutate(cardinal = ifelse(ti %in% c(0, 90, 180, 270), 'Cardinal Targets', 'Diagonal Targets')) %>%
  group_by(TN, Block, FB, cardinal) %>%
  dplyr::summarise(Hand_mean = mean(HandFlip, na.rm = TRUE), Hand_sem = std.error(HandFlip, na.rm = TRUE) )

cardinalplot <- p1 %+% targetdata + aes(fill = factor(cardinal), group = interaction(factor(Block), factor(cardinal))) + 
  geom_point (aes(color = factor(cardinal)), size = 0.5) + 
  geom_ribbon(aes(ymin = Hand_mean - Hand_sem, ymax = Hand_mean + Hand_sem), alpha = 0.05)+ 
  labs(fill = '', color = '')+
  scale_colour_manual("",values=c('orange', 'deepskyblue4'))+
  scale_fill_manual("",values=c('orange', 'deepskyblue4'))
cardinalplot

```


#Sleep

```{r}

# Median Split: median(ft.data$Sleep[ft.data$TN == 1])

sleepdata <- ft.data %>% 
  mutate(Sleep = ifelse(Sleep <= 6, '<6', '>=6')) %>%
  group_by(TN, Block, FB, Sleep) %>%
  dplyr::summarise(Hand_mean = mean(HandFlip, na.rm = TRUE), Hand_sem = std.error(HandFlip, na.rm = TRUE) )

sleep <- p1 %+% sleepdata + aes(fill = factor(Sleep), group = interaction(factor(Block), factor(Sleep))) + 
  geom_point(aes(color = factor(Sleep)), size = 0.5) + 
  geom_ribbon(aes(ymin = Hand_mean - Hand_sem, ymax = Hand_mean + Hand_sem), alpha = 0.05) +
  labs(fill = 'Sleep(hours)', color = 'Sleep(hours)')+
  scale_color_manual( values = c("orange","deepskyblue4")) + 
  scale_fill_manual( values = c("orange",  "deepskyblue4"))
sleep

```


#Savings

```{r}
ft.data.wrepeat <- raw.data %>%        
  filter(gameIndex == "easy") %>%
  filter(numtar == 1) %>%
  filter(TN <= 90)

repeatdata <- ft.data.wrepeat %>% 
  mutate(newrepeat = ifelse(repeat. == 'First Time', 'Naive', 'Experienced') ) %>% 
  group_by(TN, Block, FB, newrepeat) %>%
  dplyr::summarise(Hand_mean = mean(HandFlip, na.rm = TRUE), Hand_sem = std.error(HandFlip, na.rm = TRUE) )

repeatplot <-  p1 %+% repeatdata + aes(fill = factor(newrepeat), group = interaction(factor(Block), factor(newrepeat))) + 
  geom_point(aes(color = factor(newrepeat)), size = 0.5) + 
  geom_ribbon(aes(ymin = Hand_mean - Hand_sem, ymax = Hand_mean + Hand_sem), alpha = 0.05) +
  labs(fill = '', color = '')+
  scale_colour_manual("",values=c('orange', 'deepskyblue4'))+
  scale_fill_manual("",values=c('orange', 'deepskyblue4'))
repeatplot

ft.data.wrepeat %>% 
  filter(TN == 1) %>%
  mutate(newrepeat = ifelse(repeat. == 'First Time', 'Naive', 'Experienced') ) %>%
  ggplot(aes(x=newrepeat, fill=as.factor(cyl))) +
  theme_minimal() +
  geom_bar( fill=rgb(0.1,0.4,0.5,0.7) ) +
  scale_y_continuous(breaks = c(0, 100, 200, 300, 400, 500)) + 
  labs(x= 'Repeat Users')


```

#Vision

```{r}

visiondata <- ft.data %>% 
  group_by(TN, Block, FB, vision) %>%
  dplyr::summarise(Hand_mean = mean(HandFlip, na.rm = TRUE), Hand_sem = std.error(HandFlip, na.rm = TRUE) )

vision_plot <- p1 %+% visiondata + aes(fill = factor(vision), group = interaction(factor(Block), factor(vision))) + 
  geom_point(aes(color = factor(vision)), size = 0.5) + 
  geom_ribbon(aes(ymin = Hand_mean - Hand_sem, ymax = Hand_mean + Hand_sem), alpha = 0.05) +
  labs(fill = 'Corrected Vision', color = 'Corrected Vision')+
  scale_colour_manual("",values=c('orange', 'deepskyblue4'))+
  scale_fill_manual("",values=c('orange', 'deepskyblue4'))
vision_plot


```
 
 
#Gaming

```{r}

compgamesdata <- ft.data %>%
  group_by(TN, Block, FB, videogames) %>%
  dplyr::summarise(Hand_mean = mean(HandFlip, na.rm = TRUE), Hand_sem = std.error(HandFlip, na.rm = TRUE) )

game_plot <- p1 %+% compgamesdata + aes(fill = videogames, group = interaction(factor(Block), videogames)) + 
  geom_point(aes(color = videogames), size = 0.5) + 
  geom_ribbon(aes(ymin = Hand_mean - Hand_sem, ymax = Hand_mean + Hand_sem), alpha = 0.05) +
  labs(fill = 'Gaming Frequency', color = 'Gaming Frequency') +
  scale_color_gradient(low = "grey62", high = "deepskyblue4") + 
  scale_fill_gradient(low = "grey62", high = "deepskyblue4") 
game_plot


```

#Hours of Comp

```{r}

compusagedata <- ft.data %>% 
  group_by(TN, Block, FB, ComputerUsage) %>%
  dplyr::summarise(Hand_mean = mean(HandFlip, na.rm = TRUE), Hand_sem = std.error(HandFlip, na.rm = TRUE) ) %>%
  drop_na()

compplot <- p1 %+% compusagedata + aes(fill = ComputerUsage, group = interaction(factor(Block), ComputerUsage)) + 
  geom_point(aes(color = ComputerUsage), size = 0.5) + 
  geom_ribbon(aes(ymin = Hand_mean - Hand_sem, ymax = Hand_mean + Hand_sem), alpha = 0.05) +
  scale_color_gradient() +
  scale_fill_gradient()
compplot
```

#Education

```{r}

educationdata <- ft.data %>%
  group_by(TN, Block, FB, education) %>%
  dplyr::summarise(Hand_mean = mean(HandFlip, na.rm = TRUE), Hand_sem = std.error(HandFlip, na.rm = TRUE) ) %>%
  filter(education >=2  )%>%
  drop_na()

educationdata1 <- ft.data %>%
  group_by(TN, Block, FB, education) %>%
  dplyr::summarise(Hand_mean = mean(HandFlip, na.rm = TRUE), Hand_sem = std.error(HandFlip, na.rm = TRUE) ) %>%
  filter(education ==1 )%>%
  drop_na()

eduplot <- p1 %+% educationdata + aes(fill = education, group = interaction(factor(Block), education)) + 
  geom_point(aes(color = education), size = 0.5) + 
  geom_ribbon(aes(ymin = Hand_mean - Hand_sem, ymax = Hand_mean + Hand_sem), alpha = 0.05)+
  geom_point(data = educationdata1, aes(color = education), size = 0.5) + 
  geom_ribbon(data = educationdata1 ,aes(ymin = Hand_mean - Hand_sem, ymax = Hand_mean + Hand_sem), alpha = 0.1)+
  labs(fill = '', color = '')+
  scale_color_gradient(low = "grey62", high = "deepskyblue4") + 
  scale_fill_gradient(low = "grey62", high = "deepskyblue4")
eduplot
```

#Clumsy

```{r}

clumsydata <- ft.data %>% 
  group_by(TN, Block, FB, clumsy) %>%
  dplyr::summarise(Hand_mean = mean(HandFlip, na.rm = TRUE), Hand_sem = std.error(HandFlip, na.rm = TRUE) )

clumsyplot <- p1 %+% clumsydata + aes(fill = clumsy, group = interaction(factor(Block), clumsy)) + 
  geom_point(aes(color = clumsy), size = 0.5) + 
  geom_ribbon(aes(ymin = Hand_mean - Hand_sem, ymax = Hand_mean + Hand_sem), alpha = 0.05)+
  scale_color_gradient(low = "grey62", high = "deepskyblue4") + 
  scale_fill_gradient(low = "grey62", high = "deepskyblue4")+
  call_aesthethics(16) +
  theme(axis.text.x = element_text(angle = 45, hjust = 0.95), legend.position = 'none')
clumsyplot

```

#Major

```{r}

majordata <- ft.data %>% 
  mutate(newmajor = major ) %>%
  group_by(TN, Block, FB, newmajor) %>%
  dplyr::summarise(Hand_mean = mean(HandFlip, na.rm = TRUE), Hand_sem = std.error(HandFlip, na.rm = TRUE) ) 

majorplot <- p1 %+% majordata + aes(fill = newmajor, group = interaction(factor(Block), newmajor)) + 
  geom_point(aes(color = newmajor), size = 0.5) + 
  geom_ribbon(aes(ymin = Hand_mean - Hand_sem, ymax = Hand_mean + Hand_sem), alpha = 0.05) + 
  labs(fill = '', color = '')+
  scale_colour_manual("",values=c( 'deepskyblue4','orange', 'grey40', 'firebrick4', 'salmon', 'darkolivegreen4'))+
  scale_fill_manual("",values=c( 'deepskyblue4', 'orange', 'grey40', 'firebrick4', 'salmon', 'darkolivegreen4'))
majorplot

```


#Race

```{r}

racedata <- ft.data %>% 
  filter(racialorigin %in% c('asian', 'white', 'multiple', 'latinx')) %>%
  group_by(TN, Block, FB, racialorigin) %>%
  dplyr::summarise(Hand_mean = mean(HandFlip, na.rm = TRUE), Hand_sem = std.error(HandFlip, na.rm = TRUE) ) 

raceplot <-p1 %+% racedata + aes(fill = racialorigin, group = interaction(factor(Block), racialorigin)) + 
  geom_point(aes(color = racialorigin), size = 0.5) + 
  geom_ribbon(aes(ymin = Hand_mean - Hand_sem, ymax = Hand_mean + Hand_sem), alpha = 0.05) +
  scale_colour_manual("",values=c( 'deepskyblue4','orange', 'grey40', 'firebrick3'))+
  scale_fill_manual("",values=c( 'deepskyblue4', 'orange', 'grey40', 'firebrick3'))
raceplot

```


#Browser

```{r}

browserdata <- ft.data %>% 
  group_by(TN, Block, FB, browsertype) %>%
  dplyr::summarise(Hand_mean = mean(HandFlip, na.rm = TRUE), Hand_sem = std.error(HandFlip, na.rm = TRUE) ) 

browserplot <- p1 %+% browserdata + aes(fill = as.factor(browsertype), group = interaction(factor(Block), as.factor(browsertype))) + 
  geom_point(aes(color = as.factor(browsertype)), size = 0.5) + 
  geom_ribbon(aes(ymin = Hand_mean - Hand_sem, ymax = Hand_mean + Hand_sem), alpha = 0.05)
browserplot

```


#Rating

```{r}

ratingdata <- ft.data %>%
  group_by(TN, Block, FB, rating) %>%
  dplyr::summarise(Hand_mean = mean(HandFlip, na.rm = TRUE), Hand_sem = std.error(HandFlip, na.rm = TRUE))

ratingplot <-p1 %+% ratingdata + aes(fill = rating, group = interaction(factor(Block), rating)) + 
  geom_point(aes(color = rating), size = 0.5) + 
  geom_ribbon(aes(ymin = Hand_mean - Hand_sem, ymax = Hand_mean + Hand_sem), alpha = 0.05)+ 
  labs(fill = 'Rating', color = 'Rating')+
  scale_color_gradient(low = "grey62", high = "deepskyblue4") + 
  scale_fill_gradient(low = "grey62", high = "deepskyblue4") +
  call_aesthethics(16) +
  theme(axis.text.x = element_text(angle = 45, hjust = 0.95), legend.position = 'none')
ratingplot

```
